# Generated by Django 4.1 on 2022-09-03 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='advertisement',
            options={'verbose_name': 'Обьявление', 'verbose_name_plural': 'Обьявления'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='draft',
            field=models.BooleanField(default=True),
        ),
    ]
